# hypridle.conf

# Options
# - timeout: time in seconds to trigger
# - on-timeout: action to execute on trigger
# - on-resume: action to execute on activity after trigger 

listener {
	timeout = 900				# 15 mins
	on-timeout = brightnessctl set 10%	# lower brightness
	on-resume = brightnessctl set 100%	# restore brightness
}

listener {
	timeout = 1200				# 20 mins
	on-timeout = hyprlock			# lock screen (unlock is handled by hyprlock itself)
}

listener {
	timeout = 1500				# 25 mins
	on-timeout = brightnessctl set 0%	# turn off screen
	on-resume = brightnessctl set 100%	# turn on screen
}
