# Save location
HYPRSHOT_DIR = Images/Screenshots

################################################################################
#                                   Keybinds                                   #
################################################################################

# Screenshot a window
bind = , PRINT, exec, hyprshot -m window
